import { getColumnNumber } from "@/lib/utils";

export const DEFAULT_TICKET_COLORS = [
  "#3b82f6",
  "#10b981",
  "#f59e0b",
  "#ef4444",
  "#8b5cf6",
  "#06b6d4",
  "#84cc16",
  "#f97316",
  "#ec4899",
  "#6b7280",
];

export const STUDENT_LIST_SHEET_ID =
  "18iaTj9XVwis4yHxJrNcpp9DQidKFGCxaHcwFrnUix1Y";
export const CHECKIN_SHEET_ID = "1Tds2lU1PDyu6nhFzQPO6TnA1jIoU38I8yWurPQD3oVE";
export const CHECKIN_SHEET_NAME = "Check-in";

export const STUDENT_LIST_SHEET_NAME = "Student list";

export const STUDENT_LIST_STUDENT_NAME_COLUMN = "B";
export const STUDENT_LIST_STUDENT_ID_COLUMN = "A";
export const STUDENT_LIST_STUDENT_GENDER_COLUMN = "C";
export const STUDENT_LIST_STUDENT_HOMEROOM_COLUMN = "D";
export const STUDENT_LIST_STUDENT_EMAIL_COLUMN = "E";

export const STUDENT_LIST_STUDENT_NAME_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_NAME_COLUMN
);
export const STUDENT_LIST_STUDENT_ID_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_ID_COLUMN
);
export const STUDENT_LIST_STUDENT_GENDER_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_GENDER_COLUMN
);
export const STUDENT_LIST_STUDENT_HOMEROOM_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_HOMEROOM_COLUMN
);
export const STUDENT_LIST_STUDENT_EMAIL_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_EMAIL_COLUMN
);

export const OFFLINE_SALES_SHEET_ID =
  "1K3kNv-klSmu2TT3_fKwFJ9IDHkeZIeGRDFoOWzMVUT8";
export const OFFLINE_SALES_STAFF_SHEET_NAME = "Staff điền form";
export const OFFLINE_SALES_ORDER_SHEET_NAME = "Tổng sales offline";
export const OFFLINE_SALES_TICKET_INFO_SHEET_NAME = "Thông tin vé offline";
export const OFFLINE_SALES_EVENT_INFO_SHEET_NAME = "Thông tin sự kiện";

export const OFFLINE_SALES_EVENT_INFO_INFO_COLUMN = "A";

export const OFFLINE_SALES_EVENT_INFO_INFO_INDEX = getColumnNumber(
  OFFLINE_SALES_EVENT_INFO_INFO_COLUMN
);

export const OFFLINE_SALES_STAFF_EMAIL_COLUMN = "A";
export const OFFLINE_SALES_STAFF_NAME_COLUMN = "B";

export const OFFLINE_SALES_STAFF_EMAIL_INDEX = getColumnNumber(
  OFFLINE_SALES_STAFF_EMAIL_COLUMN
);
export const OFFLINE_SALES_STAFF_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_STAFF_NAME_COLUMN
);

export const OFFLINE_SALES_ORDER_SUBMIT_TIME_COLUMN = "A";
export const OFFLINE_SALES_ORDER_STAFF_NAME_COLUMN = "B";
export const OFFLINE_SALES_ORDER_MEDIUM_TYPE_COLUMN = "C";
export const OFFLINE_SALES_ORDER_BUYER_NAME_COLUMN = "D";
export const OFFLINE_SALES_ORDER_BUYER_CLASS_COLUMN = "E";
export const OFFLINE_SALES_ORDER_BUYER_EMAIL_COLUMN = "F";
export const OFFLINE_SALES_ORDER_BUYER_ID_COLUMN = "G";
export const OFFLINE_SALES_ORDER_TICKET_TYPE_COLUMN = "H";
export const OFFLINE_SALES_ORDER_NOTICE_COLUMN = "I";

export const OFFLINE_SALES_ORDER_SUBMIT_TIME_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_SUBMIT_TIME_COLUMN
);
export const OFFLINE_SALES_ORDER_STAFF_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_STAFF_NAME_COLUMN
);
export const OFFLINE_SALES_ORDER_MEDIUM_TYPE_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_MEDIUM_TYPE_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_NAME_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_CLASS_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_CLASS_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_EMAIL_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_EMAIL_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_ID_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_ID_COLUMN
);
export const OFFLINE_SALES_ORDER_TICKET_TYPE_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_TICKET_TYPE_COLUMN
);
export const OFFLINE_SALES_ORDER_NOTICE_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_NOTICE_COLUMN
);

export const OFFLINE_SALES_TICKET_INFO_NAME_COLUMN = "A";
export const OFFLINE_SALES_TICKET_INFO_PRICE_COLUMN = "B";
export const OFFLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN = "C";

export const OFFLINE_SALES_TICKET_INFO_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_NAME_COLUMN
);
export const OFFLINE_SALES_TICKET_INFO_PRICE_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_PRICE_COLUMN
);
export const OFFLINE_SALES_TICKET_INFO_CLASS_RANGE_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN
);

export const ONLINE_SALES_SHEET_ID =
  "116hld07P2NlEdkmq-OB2XU03udwMptDk3k9IOkepIzc";
export const ONLINE_SALES_ORDER_SHEET_NAME = "Tổng sales online";
export const ONLINE_SALES_TICKET_INFO_SHEET_NAME = "Thông tin vé online";
export const ONLINE_SALES_EVENT_INFO_SHEET_NAME = "Thông tin sự kiện";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_SHEET_NAME =
  "Thông tin form";
export const ONLINE_SALES_COORDINATOR_SHEET_NAME = "Coordinator bán vé online";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_MONEY_TRANSFER_IMAGE_COLUMN =
  "A";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_BANNER_COLUMN = "B";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_BACKGROUND_COLUMN = "C";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_HEADER_BACKGROUND_COLUMN =
  "D";
export const ONLINE_SALES_COORDINATOR_EMAIL_COLUMN = "A";
export const ONLINE_SALES_COORDINATOR_NAME_COLUMN = "B";

export const ONLINE_SALES_COORDINATOR_EMAIL_INDEX = getColumnNumber(
  ONLINE_SALES_COORDINATOR_EMAIL_COLUMN
);
export const ONLINE_SALES_COORDINATOR_NAME_INDEX = getColumnNumber(
  ONLINE_SALES_COORDINATOR_NAME_COLUMN
);

export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_MONEY_TRANSFER_IMAGE_INDEX =
  getColumnNumber(
    ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_MONEY_TRANSFER_IMAGE_COLUMN
  );
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_BANNER_INDEX =
  getColumnNumber(ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_BANNER_COLUMN);
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_BACKGROUND_INDEX =
  getColumnNumber(ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_BACKGROUND_COLUMN);
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_HEADER_BACKGROUND_INDEX =
  getColumnNumber(
    ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_HEADER_BACKGROUND_COLUMN
  );

export const ONLINE_SALES_EVENT_INFO_INFO_COLUMN = "A";

export const ONLINE_SALES_EVENT_INFO_INFO_INDEX = getColumnNumber(
  ONLINE_SALES_EVENT_INFO_INFO_COLUMN
);

export const ONLINE_SALES_TICKET_INFO_NAME_COLUMN = "A";
export const ONLINE_SALES_TICKET_INFO_PRICE_COLUMN = "B";
export const ONLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN = "C";

export const ONLINE_SALES_TICKET_INFO_NAME_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_NAME_COLUMN
);
export const ONLINE_SALES_TICKET_INFO_PRICE_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_PRICE_COLUMN
);
export const ONLINE_SALES_TICKET_INFO_CLASS_RANGE_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN
);

export const ONLINE_SALES_ORDER_SUBMIT_TIME_COLUMN = "A";
export const ONLINE_SALES_ORDER_BUYER_NAME_COLUMN = "B";
export const ONLINE_SALES_ORDER_BUYER_CLASS_COLUMN = "C";
export const ONLINE_SALES_ORDER_BUYER_EMAIL_COLUMN = "D";
export const ONLINE_SALES_ORDER_BUYER_ID_COLUMN = "E";
export const ONLINE_SALES_ORDER_TICKET_TYPE_COLUMN = "F";
export const ONLINE_SALES_ORDER_PROOF_OF_PAYMENT_IMAGE_COLUMN = "G";
export const ONLINE_SALES_ORDER_CONFIRMATION_IMAGE_COLUMN = "H";
export const ONLINE_SALES_ORDER_HAS_BEEN_VERIFIED_COLUMN = "I";
export const ONLINE_SALES_ORDER_REJECTION_REASON_COLUMN = "J";

export const ONLINE_SALES_ORDER_SUBMIT_TIME_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_SUBMIT_TIME_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_NAME_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_NAME_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_CLASS_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_CLASS_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_EMAIL_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_EMAIL_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_ID_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_ID_COLUMN
);
export const ONLINE_SALES_ORDER_TICKET_TYPE_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_TICKET_TYPE_COLUMN
);
export const ONLINE_SALES_ORDER_PROOF_OF_PAYMENT_IMAGE_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_PROOF_OF_PAYMENT_IMAGE_COLUMN
);
export const ONLINE_SALES_ORDER_CONFIRMATION_IMAGE_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_CONFIRMATION_IMAGE_COLUMN
);
export const ONLINE_SALES_ORDER_REJECTION_REASON_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_REJECTION_REASON_COLUMN
);
export const ONLINE_SALES_ORDER_HAS_BEEN_VERIFIED_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_HAS_BEEN_VERIFIED_COLUMN
);

export const NOT_STAFF_ERROR = "not-staff";
export const NOT_LOGGED_IN_ERROR = "not-logged-in";
export const INVALID_TICKET_DUE_TO_INVALID_CLASS = "Lớp không hợp lệ!";
export const NOT_STUDENT_IN_SCHOOL =
  "Không phải học sinh trong trường, vui lòng tự điền";

export const VERIFICATION_FAILED = "Đã bị từ chối";
export const VERIFICATION_PENDING = "Đang đợi xác minh";
export const VERIFICATION_APPROVED = "Xác minh thành công";
