import { getColumnNumber } from "@/lib/utils";
import { DB_ORDER_STATUS, VERIFICATION_STATUS } from "./types";

export const DEFAULT_TICKET_COLORS = [
  "#3b82f6",
  "#10b981",
  "#f59e0b",
  "#ef4444",
  "#8b5cf6",
  "#06b6d4",
  "#84cc16",
  "#f97316",
  "#ec4899",
  "#6b7280",
];

export const STUDENT_LIST_SHEET_ID =
  "18iaTj9XVwis4yHxJrNcpp9DQidKFGCxaHcwFrnUix1Y";
export const CHECKIN_SHEET_ID = "1Tds2lU1PDyu6nhFzQPO6TnA1jIoU38I8yWurPQD3oVE";
export const TEACHER_VERIFICATION_SHEET_ID =
  "1vSIBWKdBZEh6Yh_PVclb-rOgebZeCCp1tHPm-AaSNio";

export const TEACHER_VERIFICATION_SHEET_NAME = "sheet1";
export const CHECKIN_SHEET_NAME = "Check-in";
export const STUDENT_LIST_SHEET_NAME = "Student list";

export const TEACHER_VERIFICATION_STUDENT_NAME_COLUMN = "C";
export const TEACHER_VERIFICATION_STUDENT_ID_COLUMN = "B";
export const TEACHER_VERIFICATION_STUDENT_HOMEROOM_COLUMN = "D";
export const TEACHER_VERIFICATION_STUDENT_ACCEPT_STATUS_COLUMN = "E";
export const TEACHER_VERIFICATION_STUDENT_REJECT_STATUS_COLUMN = "F";
export const TEACHER_VERIFICATION_TEACHER_NOTICE_COLUMN = "G";

export const TEACHER_VERIFICATION_STUDENT_NAME_INDEX = getColumnNumber(
  TEACHER_VERIFICATION_STUDENT_NAME_COLUMN
);
export const TEACHER_VERIFICATION_STUDENT_ID_INDEX = getColumnNumber(
  TEACHER_VERIFICATION_STUDENT_ID_COLUMN
);
export const TEACHER_VERIFICATION_STUDENT_HOMEROOM_INDEX = getColumnNumber(
  TEACHER_VERIFICATION_STUDENT_HOMEROOM_COLUMN
);
export const TEACHER_VERIFICATION_STUDENT_ACCEPT_STATUS_INDEX = getColumnNumber(
  TEACHER_VERIFICATION_STUDENT_ACCEPT_STATUS_COLUMN
);

export const TEACHER_VERIFICATION_STUDENT_REJECT_STATUS_INDEX = getColumnNumber(
  TEACHER_VERIFICATION_STUDENT_REJECT_STATUS_COLUMN
);

export const TEACHER_VERIFICATION_TEACHER_NOTICE_INDEX = getColumnNumber(
  TEACHER_VERIFICATION_TEACHER_NOTICE_COLUMN
);

export const STUDENT_LIST_STUDENT_NAME_COLUMN = "B";
export const STUDENT_LIST_STUDENT_ID_COLUMN = "A";
export const STUDENT_LIST_STUDENT_GENDER_COLUMN = "C";
export const STUDENT_LIST_STUDENT_HOMEROOM_COLUMN = "D";
export const STUDENT_LIST_STUDENT_EMAIL_COLUMN = "E";

export const STUDENT_LIST_STUDENT_NAME_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_NAME_COLUMN
);
export const STUDENT_LIST_STUDENT_ID_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_ID_COLUMN
);
export const STUDENT_LIST_STUDENT_GENDER_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_GENDER_COLUMN
);
export const STUDENT_LIST_STUDENT_HOMEROOM_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_HOMEROOM_COLUMN
);
export const STUDENT_LIST_STUDENT_EMAIL_INDEX = getColumnNumber(
  STUDENT_LIST_STUDENT_EMAIL_COLUMN
);

export const OFFLINE_SALES_SHEET_ID =
  "1K3kNv-klSmu2TT3_fKwFJ9IDHkeZIeGRDFoOWzMVUT8";
export const OFFLINE_SALES_STAFF_SHEET_NAME = "Staff điền form";
export const OFFLINE_SALES_ORDER_SHEET_NAME = "Tổng sales offline";
export const OFFLINE_SALES_TICKET_INFO_SHEET_NAME = "Thông tin vé offline";
export const OFFLINE_SALES_EVENT_INFO_SHEET_NAME = "Thông tin sự kiện";
export const OFFLINE_SALES_EMAIL_INFO_SHEET_NAME = "Thông tin email";

export const OFFLINE_SALES_EMAIL_INFO_EMAIL_BANNER_IMAGE_COLUMN = "A";
export const OFFLINE_SALES_EMAIL_INFO_EMAIL_SUBJECT_COLUMN = "B";

export const OFFLINE_SALES_EMAIL_INFO_EMAIL_BANNER_IMAGE_INDEX =
  getColumnNumber(OFFLINE_SALES_EMAIL_INFO_EMAIL_BANNER_IMAGE_COLUMN);
export const OFFLINE_SALES_EMAIL_INFO_EMAIL_SUBJECT_INDEX = getColumnNumber(
  OFFLINE_SALES_EMAIL_INFO_EMAIL_SUBJECT_COLUMN
);

export const OFFLINE_SALES_EVENT_INFO_EVENT_NAME_COLUMN = "A";
export const OFFLINE_SALES_EVENT_INFO_EVENT_DATE_COLUMN = "B";
export const OFFLINE_SALES_EVENT_INFO_EVENT_YEAR_COLUMN = "C";
export const OFFLINE_SALES_EVENT_INFO_EVENT_TYPE_COLUMN = "D";

export const OFFLINE_SALES_EVENT_INFO_EVENT_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_EVENT_INFO_EVENT_NAME_COLUMN
);
export const OFFLINE_SALES_EVENT_INFO_EVENT_DATE_INDEX = getColumnNumber(
  OFFLINE_SALES_EVENT_INFO_EVENT_DATE_COLUMN
);
export const OFFLINE_SALES_EVENT_INFO_EVENT_YEAR_INDEX = getColumnNumber(
  OFFLINE_SALES_EVENT_INFO_EVENT_YEAR_COLUMN
);
export const OFFLINE_SALES_EVENT_INFO_EVENT_TYPE_INDEX = getColumnNumber(
  OFFLINE_SALES_EVENT_INFO_EVENT_TYPE_COLUMN
);

export const OFFLINE_SALES_STAFF_EMAIL_COLUMN = "A";
export const OFFLINE_SALES_STAFF_NAME_COLUMN = "B";

export const OFFLINE_SALES_STAFF_EMAIL_INDEX = getColumnNumber(
  OFFLINE_SALES_STAFF_EMAIL_COLUMN
);
export const OFFLINE_SALES_STAFF_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_STAFF_NAME_COLUMN
);

export const OFFLINE_SALES_ORDER_SUBMIT_TIME_COLUMN = "A";
export const OFFLINE_SALES_ORDER_STAFF_NAME_COLUMN = "B";
export const OFFLINE_SALES_ORDER_MEDIUM_TYPE_COLUMN = "C";
export const OFFLINE_SALES_ORDER_BUYER_NAME_COLUMN = "D";
export const OFFLINE_SALES_ORDER_BUYER_CLASS_COLUMN = "E";
export const OFFLINE_SALES_ORDER_BUYER_EMAIL_COLUMN = "F";
export const OFFLINE_SALES_ORDER_BUYER_ID_COLUMN = "G";
export const OFFLINE_SALES_ORDER_TICKET_TYPE_COLUMN = "H";
export const OFFLINE_SALES_ORDER_NOTICE_COLUMN = "I";
export const OFFLINE_SALES_ORDER_EMAIL_STATUS_COLUMN = "J";

export const OFFLINE_SALES_ORDER_SUBMIT_TIME_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_SUBMIT_TIME_COLUMN
);
export const OFFLINE_SALES_ORDER_STAFF_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_STAFF_NAME_COLUMN
);
export const OFFLINE_SALES_ORDER_MEDIUM_TYPE_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_MEDIUM_TYPE_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_NAME_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_CLASS_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_CLASS_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_EMAIL_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_EMAIL_COLUMN
);
export const OFFLINE_SALES_ORDER_BUYER_ID_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_BUYER_ID_COLUMN
);
export const OFFLINE_SALES_ORDER_TICKET_TYPE_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_TICKET_TYPE_COLUMN
);
export const OFFLINE_SALES_ORDER_NOTICE_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_NOTICE_COLUMN
);
export const OFFLINE_SALES_ORDER_EMAIL_STATUS_INDEX = getColumnNumber(
  OFFLINE_SALES_ORDER_EMAIL_STATUS_COLUMN
);

export const OFFLINE_SALES_TICKET_INFO_NAME_COLUMN = "A";
export const OFFLINE_SALES_TICKET_INFO_PRICE_COLUMN = "B";
export const OFFLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN = "C";
export const OFFLINE_SALES_TICKET_INFO_INCLUDE_CONCERT_COLUMN = "D";
export const OFFLINE_SALES_TICKET_INFO_MAX_QUANTITY_COLUMN = "E";

export const OFFLINE_SALES_TICKET_INFO_NAME_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_NAME_COLUMN
);
export const OFFLINE_SALES_TICKET_INFO_PRICE_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_PRICE_COLUMN
);
export const OFFLINE_SALES_TICKET_INFO_CLASS_RANGE_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN
);
export const OFFLINE_SALES_TICKET_INFO_INCLUDE_CONCERT_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_INCLUDE_CONCERT_COLUMN
);
export const OFFLINE_SALES_TICKET_INFO_MAX_QUANTITY_INDEX = getColumnNumber(
  OFFLINE_SALES_TICKET_INFO_MAX_QUANTITY_COLUMN
);

export const ONLINE_SALES_SHEET_ID =
  "116hld07P2NlEdkmq-OB2XU03udwMptDk3k9IOkepIzc";
export const ONLINE_SALES_ORDER_SHEET_NAME = "Tổng sales online";
export const ONLINE_SALES_TICKET_INFO_SHEET_NAME = "Thông tin vé online";
export const ONLINE_SALES_EVENT_INFO_SHEET_NAME = "Thông tin sự kiện";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_SHEET_NAME =
  "Thông tin form";
export const ONLINE_SALES_COORDINATOR_SHEET_NAME = "Coordinator bán vé online";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_MONEY_TRANSFER_IMAGE_COLUMN =
  "A";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_BANNER_COLUMN = "B";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_BACKGROUND_COLUMN = "C";
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_HEADER_BACKGROUND_COLUMN =
  "D";
export const ONLINE_SALES_COORDINATOR_EMAIL_COLUMN = "A";
export const ONLINE_SALES_COORDINATOR_NAME_COLUMN = "B";

export const ONLINE_SALES_COORDINATOR_EMAIL_INDEX = getColumnNumber(
  ONLINE_SALES_COORDINATOR_EMAIL_COLUMN
);
export const ONLINE_SALES_COORDINATOR_NAME_INDEX = getColumnNumber(
  ONLINE_SALES_COORDINATOR_NAME_COLUMN
);

export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_MONEY_TRANSFER_IMAGE_INDEX =
  getColumnNumber(
    ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_MONEY_TRANSFER_IMAGE_COLUMN
  );
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_BANNER_INDEX =
  getColumnNumber(ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_INFO_BANNER_COLUMN);
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_BACKGROUND_INDEX =
  getColumnNumber(ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_BACKGROUND_COLUMN);
export const ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_HEADER_BACKGROUND_INDEX =
  getColumnNumber(
    ONLINE_SALES_EVENT_FORM_CUSTOMIZATION_HEADER_BACKGROUND_COLUMN
  );

export const ONLINE_SALES_EVENT_INFO_INFO_COLUMN = "A";

export const ONLINE_SALES_EVENT_INFO_INFO_INDEX = getColumnNumber(
  ONLINE_SALES_EVENT_INFO_INFO_COLUMN
);

export const ONLINE_SALES_TICKET_INFO_NAME_COLUMN = "A";
export const ONLINE_SALES_TICKET_INFO_PRICE_COLUMN = "B";
export const ONLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN = "C";
export const ONLINE_SALES_TICKET_INFO_INCLUDE_CONCERT_COLUMN = "D";
export const ONLINE_SALES_TICKET_INFO_MAX_QUANTITY_COLUMN = "E";

export const ONLINE_SALES_TICKET_INFO_NAME_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_NAME_COLUMN
);
export const ONLINE_SALES_TICKET_INFO_PRICE_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_PRICE_COLUMN
);
export const ONLINE_SALES_TICKET_INFO_CLASS_RANGE_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_CLASS_RANGE_COLUMN
);
export const ONLINE_SALES_TICKET_INFO_INCLUDE_CONCERT_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_INCLUDE_CONCERT_COLUMN
);
export const ONLINE_SALES_TICKET_INFO_MAX_QUANTITY_INDEX = getColumnNumber(
  ONLINE_SALES_TICKET_INFO_MAX_QUANTITY_COLUMN
);

export const ONLINE_SALES_ORDER_SUBMIT_TIME_COLUMN = "A";
export const ONLINE_SALES_ORDER_BUYER_NAME_COLUMN = "B";
export const ONLINE_SALES_ORDER_BUYER_CLASS_COLUMN = "C";
export const ONLINE_SALES_ORDER_BUYER_EMAIL_COLUMN = "D";
export const ONLINE_SALES_ORDER_BUYER_ID_COLUMN = "E";
export const ONLINE_SALES_ORDER_TICKET_TYPE_COLUMN = "F";
export const ONLINE_SALES_ORDER_PROOF_OF_PAYMENT_IMAGE_COLUMN = "G";
export const ONLINE_SALES_ORDER_HAS_BEEN_VERIFIED_COLUMN = "H";
export const ONLINE_SALES_ORDER_REJECTION_REASON_COLUMN = "I";
export const ONLINE_SALES_ORDER_EMAIL_STATUS_COLUMN = "J";
export const ONLINE_SALES_ORDER_SUBMIT_TIME_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_SUBMIT_TIME_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_NAME_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_NAME_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_CLASS_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_CLASS_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_EMAIL_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_EMAIL_COLUMN
);
export const ONLINE_SALES_ORDER_BUYER_ID_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_BUYER_ID_COLUMN
);
export const ONLINE_SALES_ORDER_TICKET_TYPE_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_TICKET_TYPE_COLUMN
);
export const ONLINE_SALES_ORDER_PROOF_OF_PAYMENT_IMAGE_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_PROOF_OF_PAYMENT_IMAGE_COLUMN
);
export const ONLINE_SALES_ORDER_EMAIL_STATUS_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_EMAIL_STATUS_COLUMN
);
export const ONLINE_SALES_ORDER_REJECTION_REASON_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_REJECTION_REASON_COLUMN
);
export const ONLINE_SALES_ORDER_HAS_BEEN_VERIFIED_INDEX = getColumnNumber(
  ONLINE_SALES_ORDER_HAS_BEEN_VERIFIED_COLUMN
);

export const NOT_STAFF_ERROR = "not-staff";
export const NOT_LOGGED_IN_ERROR = "not-logged-in";
export const INVALID_TICKET_DUE_TO_INVALID_CLASS = "Class not found!";
export const ALL_TICKETS_SOLD_OUT = "Tickets sold out!";
export const SALES_INFO_FETCHING = "Loading...";
export const NOT_STUDENT_IN_SCHOOL =
  "Not a student in the school, please fill in manually";

export const VERIFICATION_FAILED = VERIFICATION_STATUS.FAILED;
export const VERIFICATION_PENDING = VERIFICATION_STATUS.PENDING;
export const VERIFICATION_APPROVED = VERIFICATION_STATUS.SUCCESS;

export const PENDING_EMAIL_STATUS = "Chưa gửi email";
export const SENT_EMAIL_STATUS = "Đã gửi email";
export const FAILED_EMAIL_STATUS = "Lỗi gửi email";

export const VERIFICATION_FAILED_DB = DB_ORDER_STATUS.FAILED;
export const VERIFICATION_PENDING_DB = DB_ORDER_STATUS.PENDING;
export const VERIFICATION_APPROVED_DB = DB_ORDER_STATUS.SUCCESS;
export const SILENCIO_HAUNTED_HOUSE_QUEUE_MANAGER_URL =
  "https://silencio-vcp.vercel.app";

// Spreadsheet & back-up Links
export const SPREADSHEET_LINKS = [
  {
    label: "Offline sales sheet",
    href: `https://docs.google.com/spreadsheets/d/${OFFLINE_SALES_SHEET_ID}`,
  },
  {
    label: "Online sales sheet",
    href: `https://docs.google.com/spreadsheets/d/${ONLINE_SALES_SHEET_ID}`,
  },
  {
    label: "Sheet check-in",
    href: `https://docs.google.com/spreadsheets/d/${CHECKIN_SHEET_ID}`,
  },
  {
    label: "Teacher verification sheet",
    href: `https://docs.google.com/spreadsheets/d/${TEACHER_VERIFICATION_SHEET_ID}`,
  },
  {
    label: "Form backup",
    href: `https://docs.google.com/forms/d/e/1FAIpQLSfpRH5kU4lqvTnwgs_lmOHtYjo_RqZ2EDGlS6d7hewavX6zBg/viewform?usp=sharing&ouid=103069438122563507136`,
  },
  {
    label: "Backup sheet",
    href: `https://docs.google.com/spreadsheets/d/1jV3n7OyCSe5WSVTNqBtb9csoIgye1-ue7VdntDPCzrY/edit?usp=sharing`,
  },
];
